{
 "title": "K6",
 "panels": [
  {
   "title": "VUs",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_vus", "legendFormat": "VU" }
   ]
  },
  {
   "title": "Iterations/second",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (scenario) (rate(k6_iterations[$interval]))",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Dropped iterations",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (scenario) (k6_dropped_iterations)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Iteration Duration 95%ile",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (scenario) (k6_iteration_duration_p95)",
     "legendFormat": "{{scenario}}"
    }
   ]
  }
 ]
}
{
 "title": "Workflows",
 "panels": [
  {
   "title": "Workflow Completion Rate",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workflow_type) (rate(temporal_workflow_completed[$interval]))",
     "legendFormat": "{{workflow_type}}"
    }
   ]
  }
 ]
}
{
 "title": "Service",
 "panels": [
  {
   "title": "Progress Event Latency p95",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_request_latency_bucket{operation=~\"RecordActivityTaskHeartbeat|RespondWorkflowTaskCompleted|RespondActivityTaskCompleted\"}[$interval])) by (namespace, operation, le))",
     "legendFormat": "{{namespace}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Timer Task Latency p95",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_latency_queue_bucket{operation=~\"Timer.*\"}[$interval])) by (namespace, operation, le))",
     "legendFormat": "{{namespace}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Transfer Task Latency p95",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_latency_queue_bucket{operation=~\"Transfer.*\"}[$interval])) by (namespace, operation, le))",
     "legendFormat": "{{namespace}}: {{operation}}"
    }
   ]
  }
 ]
}
{
 "title": "Workers",
 "panels": [
  {
   "title": "Workflow Task Schedule to Start Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_workflow_task_schedule_to_start_latency_sum[$interval])",
     "legendFormat": "{{workflow_type}}"
    }
   ]
  },
  {
   "title": "Activity Task Schedule to Start Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (activity_type) (rate(temporal_activity_schedule_to_start_latency_sum[$interval]))",
     "legendFormat": "{{activity_type}}"
    }
   ]
  },
  {
   "title": "Workflow Task Slots Available",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (temporal_worker_task_slots_available{namespace!=\"temporal_system\",worker_type=\"WorkflowWorker\"})",
     "legendFormat": "{{namespace}}: {{task_queue}}"
    }
   ]
  },
  {
   "title": "Activity Task Slots Available",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (temporal_worker_task_slots_available{namespace!=\"temporal_system\",worker_type=\"ActivityWorker\"})",
     "legendFormat": "{{namespace}}: {{task_queue}}"
    }
   ]
  }
 ]
}