{
 "title": "SDK Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Namespace" },
   { "name": "WorkflowType" }
  ]
 },
 "panels": [
  { "title": "RPC Overview ($Namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Vs Failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(temporal_request[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(temporal_request_failure[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "RPC Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) ((rate(temporal_request[5m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Failures Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(temporal_request_failure[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Latencies ($Namespace)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (temporal_namespace, operation, le) (rate(temporal_request_latency_bucket[5m])))",
     "legendFormat": "{{ temporal_namespace }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Completion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(temporal_workflow_completed[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(temporal_workflow_failed[5m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(rate(temporal_workflow_canceled[5m]))",
       "legendFormat": "cancelled"
      },
      {
       "expr": "sum(rate(temporal_workflow_continue_as_new[5m]))",
       "legendFormat": "continued_as_new"
      }
     ]
    },
    {
     "title": "Workflow End-To-End Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_endtoend_latency_bucket[5m])) by (temporal_namespace, workflow_type, le))",
       "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Success By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, workflow_type) (rate(temporal_workflow_completed[5m]))",
       "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Failures By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, workflow_type) (rate(temporal_workflow_failed[5m]))",
       "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
      }
     ]
    }
   ]
  },
  { "title": "Workflow Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Workflow Task Throughput By WorkflowType",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_namespace, workflow_type) (rate(temporal_workflow_task_queue_poll_succeed[5m]))",
     "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
    }
   ]
  },
  {
   "title": "Workflow Task Throughput By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_namespace) (rate(temporal_workflow_task_queue_poll_succeed[5m]))",
     "legendFormat": "{{ temporal_namespace }}"
    }
   ]
  },
  {
   "title": "Empty Polls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_namespace) (rate(temporal_workflow_task_queue_poll_empty[5m]))",
     "legendFormat": "Empty Poll - {{ temporal_namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Task Execution Latency By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket[5m])) by (temporal_namespace, le))",
     "legendFormat": "{{ temporal_namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Task Backlog By Workflow Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket[5m])) by (temporal_namespace, workflow_type, le))",
     "legendFormat": "{{ temporal_namespace }} -- {{ workflow_type }}"
    }
   ]
  },
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Activity Throughput By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_namespace) (rate(temporal_activity_execution_latency_count[5m]))",
     "legendFormat": "latency count"
    }
   ]
  },
  {
   "title": "Activity Throughput By Activity Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_namespace, activity_type) (rate(temporal_activity_execution_latency_count[5m]))",
     "legendFormat": "{{ activity_type }}"
    }
   ]
  },
  {
   "title": "Failed Activity by Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_namespace, activity_type) (rate(temporal_activity_execution_failed[5m]))",
     "legendFormat": "{{ temporal_namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Activity Execution Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_bucket[5m])) by (temporal_namespace, activity_type, le))",
     "legendFormat": "{{ temporal_namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Activity End-To-End Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_endtoend_latency_bucket[5m])) by (temporal_namespace, activity_type, le))"
    }
   ]
  },
  { "title": "Activity Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Empty Activity Polls By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_namespace) (rate(temporal_activity_poll_no_task[5m]))",
     "legendFormat": "{{ temporal_namespace }}"
    }
   ]
  },
  {
   "title": "Activity Task Backlog By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket[5m])) by (temporal_namespace, le))"
    }
   ]
  },
  {
   "title": "Activity Task Backlog By Activity Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket[5m])) by (temporal_namespace, activity_type, le))",
     "legendFormat": "{{ activity_type }}"
    }
   ]
  }
 ]
}